// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'referralCode': String,
    'fire_token': String,
    'appleID': String,
    'first_use': Boolean,
    'credits': Number,
    'password': String,
    'stripe_customerId': String,
    'level': Number,
    'name': String,
    'phone_num': String,
    'city': String,
    'referralCodeRedeems': Boolean,
    'createdAt': Date,
    'discount': Number,
    'last_seen': Date,
    'public_key': String,
    'otp': Number,
    'email': String,
    'discount_code': String,
    'surname': String,
    'verified': Boolean,
    'accountLevel': Number,
    'role': String,
  }, {
    timestamps: false,
  });

  return mongoose.model('users', schema, 'users');
};
